diary_events/models.py
from sqlalchemy.sql.functions import current_date

from database import db


class Events(db.Model):
    __tablename__ = 'Events'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String, unique=False, nullable=False)
    date_field = db.Column(db.String, unique=False, index=True)
    start_date = db.Column(db.Date, default=current_date, nullable=False)
    end_date = db.Column(db.Date, default=current_date, nullable=False)
    classes = db.Column(db.String, nullable=False)


class EventsUser(db.Model):
    __tablename__ = 'EventsUser'

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    event_id = db.Column(db.Integer, db.ForeignKey('Events.id'), nullable=False)
    is_completed = db.Column(db.Boolean, default=False)
    

class ToDos(db.Model):
    __tablename__ = 'ToDos'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String, unique=True, nullable=False, index=True)
    password = db.Column(db.String, nullable=False)
    hash = db.Column(db.String, nullable=False, unique=True)


class ToDoUsers(db.Model):
    __tablename__ = 'ToDoUsers'

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    todo_id = db.Column(db.Integer, db.ForeignKey('ToDos.id'), nullable=False)
    role = db.Column(db.String, nullable=False, default='Performer')


class ToDoEvents(db.Model):
    __tablename__ = 'ToDoEvents'

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    todo_id = db.Column(db.Integer, db.ForeignKey('ToDos.id'), nullable=False)
    task = db.Column(db.String, nullable=False)
    status = db.Column(db.String, nullable=False, default='ToDo')

diary_events/forms.py
from datetime import date

from flask_wtf import FlaskForm
from wtforms import StringField, DateField, SubmitField
from wtforms.validators import DataRequired


class EventForm(FlaskForm):
    name = StringField("Event name", validators=[DataRequired()])
    start_date = DateField("Start date", default=date.today())
    end_date = DateField("End date")
    classes = StringField("Event class")
    submit = SubmitField("Delete")

    def validate_on_submit(self):
        result = super(EventForm, self).validate()
        if self.start_date.data > self.end_date.data if self.end_date.data else True:
            return False
        else:
            return result

diary_events/controllers.py
from flask import request, redirect, url_for, render_template, Blueprint, flash
from flask_login import login_required, current_user

from accounts.models import User
from database import db
from diary_events.models import ToDos, ToDoUsers
from diary_events.services import get_events, delete_events, save_event, create_dependence_todo_user_events, \
    prepare_todo_data, save_todo, user_add_todo, create_dependence_user_events, complete_todo_event

diary_blueprint = Blueprint('diary', __name__, template_folder='templates')


@diary_blueprint.route('/', methods=['GET'])
@login_required
def index():
    return render_template('diary_events/diary.html')


@diary_blueprint.route('/<int:month>/<int:day>/<int:year>', methods=['GET', 'POST'])
@login_required
def events(month, day, year):
    date = '{}/{}/{}'.format(month, day, year)
    event_list = get_events(current_user.id, date)
    if request.method == 'POST':
        if request.form['btn'] == 'Complete':
            print(2)
            event_id = request.form['list']
            delete_events(event_id)
            return redirect(url_for('diary.events', month=month, day=day, year=year))
        else:
            event = save_event(request)
            event.date_field = '{}/{}/{}'.format(month, day, year)
            db.session.add(event)
            db.session.commit()
            events_user = create_dependence_user_events(event.id, current_user.id, )
            db.session.add(events_user)
            db.session.commit()
            return redirect(url_for('diary.events', month=month, day=day, year=year))
    return render_template('diary_events/events.html', events=event_list)


@diary_blueprint.route('/todo/<hash_id>', methods=['GET', 'POST'])
@login_required
def todo(hash_id):
    todo_d = ToDos.query.filter_by(hash=hash_id).first()
    if request.method == 'POST':
        if request.form['btn'] == 'add':
            user = User.query.filter_by(email=request.form['mail']).first()
            try:
                user_add_todo(hash_id, user)
                create_dependence_todo_user_events(request.form['event'], user.id, todo_d.id,
                                                   status=request.form['status'])
            except Exception as e:
                flash(str(e) or 'Unknown error')
            else:
                return redirect(url_for('diary.todo', hash_id=hash_id))
        else:
            complete_todo_event(request.form['btn'])
            return redirect(url_for('diary.todo', hash_id=hash_id))
    name = User.query.filter_by(id=current_user.id).first().username
    current_event = ToDoUsers.query.filter_by(todo_id=todo_d.id, user_id=current_user.id).first()
    role = current_event.role if current_event else 'Performer'
    todos = prepare_todo_data(todo_d.id)
    return render_template('diary_events/todo.html', todos=todos, current_user_role=role, name=name)


@diary_blueprint.route('/manage', methods=['GET', 'POST'])
@login_required
def manage_todo():
    if request.method == 'POST':
        if request.form['btn'] == 'search':
            todo_hash = request.form['search_hash']
            todo_d = ToDos.query.filter_by(hash=todo_hash).first()
            if todo_d:
                return redirect(url_for('diary.todo', hash_id=todo_hash))
            else:
                flash('Incorrect hash')
        else:
            try:
                hash_todo = save_todo(request, current_user.id)
            except Exception as e:
                flash(str(e) or 'Unknown error')
            else:
                return redirect(url_for('diary.todo', hash_id=hash_todo))
    return render_template('diary_events/manage.html')

diary_events/templates/diary_events/diary.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Your Calendar</title>
    <link rel="stylesheet" href="/static/css/style.css">
  </head>
  <body>
    <div id="container">
      <div id="header">
        <a href="{{url_for('diary.manage_todo') }}">Your ToDo</a>
        <div id="monthDisplay"></div>
        <div>
          <button id="backButton">Back</button>
          <button id="nextButton">Next</button>
          <button class="btn btn-primary" onclick="history.back();" type="button">Previous page</button>

        </div>
      </div>

      <div id="weekdays">
        <div>Sunday</div>
        <div>Monday</div>
        <div>Tuesday</div>
        <div>Wednesday</div>
        <div>Thursday</div>
        <div>Friday</div>
        <div>Saturday</div>
      </div>

      <div id="calendar"></div>
    </div>

    <div id="newEventModal">
      <h2>New Event</h2>
      <input id="eventTitleInput" placeholder="Event Title"/>

      <button id="saveButton">Save</button>
      <button id="redirectButton" type="button">Redirect</button>
      <button id="cancelButton">Cancel</button>
    </div>

    <div id="deleteEventModal">
      <h2>Event</h2>

      <p id="eventText"></p>

      <button id="deleteButton">Delete</button>
      <button id="redirectButton1" type="button">Redirect</button>
      <button id="closeButton">Close</button>
    </div>

    <div id="modalBackDrop"></div>

    <script src="/static/js/calendar.min.js"></script>
  </body>
</html>

diary_events/templates/diary_events/events.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
    <title>Your Events</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/todo.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap/bootstrap.min.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.7.5/css/bootstrap-select.min.css">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.13.0/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
    <script src="https://code.jquery.com/ui/1.13.0/jquery-ui.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.7.5/js/bootstrap-select.min.js"></script>
    <script>$( function() {
    var dateFormat = "mm/dd/yy",
      from = $( "#start_date" )
        .datepicker({
          defaultDate: "+1w",
          changeMonth: true,
          numberOfMonths: 1
        })
        .on( "change", function() {
          to.datepicker( "option", "minDate", getDate( this ) );
        }),
      to = $( "#end_date" ).datepicker({
        defaultDate: "+1w",
        changeMonth: true,
        numberOfMonths: 1
      })
      .on( "change", function() {
        from.datepicker( "option", "maxDate", getDate( this ) );
      });

    function getDate( element ) {
      var date;
      try {
        date = $.datepicker.parseDate( dateFormat, element.value );
      } catch( error ) {
        date = null;
      }

      return date;
    }
  } );
  </script>
</head>
<body>
<div id="myDIV" class="header">
  <h2>My Event List</h2>
  {% if events %}<table>
      <tr><td>Id</td><td>Name<td>Start Date<td>End Date<td>Important level<td></td></tr>
      {% for event in events %}
      <tr>
        {% for element in event %}
          {% if element.name != 'id' %}
            <td>{{ element }}</td>
          {% endif %}
        {% endfor %}
      <td></tr>
      {% endfor %}
    </table>
    {% endif %}
  </div>
  <form method="post">
      <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
      <div class="mb-3"><input class="form-control" type="text" name="name" placeholder="Name" required=""></div>
      <label for="start_date">From<div class="mb-3"><input class="form-control" type="text" id="start_date" name="start_date" placeholder="Start Date"></div></label>
      <label for="end_date">To<div class="mb-3"><input class="form-control" type="text" id="end_date" name="end_date" placeholder="End Date"></div></label>
      <div class="mb-3"><input class="form-control" type="text" name="classes" placeholder="Important level" required=""></div>
      <div class="mb-3"><button class="btn profile-title" type="submit" name="btn" value="add">Save</button></div>
    </form>
    <form method="post">
    <div class="container">
        {% if events %}
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
            <select name="list" class="form-control" data-style="btn-primary" style="width:10%">
                {% for event in events %}
                        <option value="{{event[0]}}">{{ event[0] }}</option>
                    {% endfor %}
            </select>
        <button type="submit" name="btn" value="Complete" class="btn-primary" style="background-color: #3C5268FF; width:10%">Complete</button>
        {% endif %}
    </div>
    </form>
</body>
</html>

diary_events/templates/diary_events/manage.html
{% extends 'base.html' %}
    {% block title %}Manage{% endblock %}
{% block head %}
<link rel="stylesheet" href="{{url_for('static', filename='css/Pretty-Search-Form.css')}}">
{% endblock %}
{% block content %}
    <form class="search-form" method="post" style="width: 480px;height: 30px;">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
        <div class="input-group"><span class="input-group-text" style="background: rgb(233, 236, 239);"><i class="fa fa-search"></i></span><input class="form-control" name="search_hash" type="text" maxlength="7" placeholder="I am looking for a team with this hash" style="width: 220px;"><button type="submit" class="btn btn-light" name="btn" type="button" value="search" style="background: rgb(233,236,239);">Search </button></div>
    </form>
    <div class="search-form">
        <form method="post">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
            <div class="input-group mb-3" style="width: 300px;height: 30px;"><span class="input-group-text">Name</span><input type="text" class="form-control" name="name" placeholder="Team Name"></div>
            <div class="input-group mb-3" style="width: 200px;height: 30px;"><span class="input-group-text">Hash</span><input class="form-control-sm form-control" type="text" name="hash" maxlength="7" placeholder="hash" style="width: 100px;"></div>
            <div class="input-group mb-3" style="width: 400px;height: 30px;"><span class="input-group-text">Password</span><input type="password" name="password" class="form-control" placeholder="password"></div><button class="btn btn-primary" type="submit" name="btn" value="create" style="transform: perspective(0px) translate(576px) translateX(-156px) translateY(-95px);background: rgb(233,236,239);color: rgb(35,32,32);">Create</button>
        </form>
    </div>
    <div class="container"><button class="btn btn-primary" onclick="location.href={{url_for('diary.index')}}" type="button">Back To Calendar</button></div>
{%endblock%}

diary_events/templates/diary_events/todo.html
{% extends 'base.html' %}
    {% block title %}Our ToDo{% endblock %}
{% block head %}
<link rel="stylesheet" href="{{url_for('static', filename='css/todo.css')}}">
<script src="{{url_for('static', filename='js/todo.js')}}"></script>
{% endblock %}
{% block content %}
    <main role="main" class="container extra-bottom">
      <h1 class="mt-5">TODO List</h1>
      <p><mark>Do it now.</mark></p>
    </main>

    {% if current_user_role == 'Creator' %}
    <div class="container">

        <!-- Button trigger modal -->
        <div style="text-align: right;">
        <button type="button"class="btn btn-outline-info btn-sm" data-bs-toggle="modal"
														data-bs-target="#task-modal" data-source="New Task">Add Task</button>
        </div>
        <form method="post">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
        <div class="modal fade" id="task-modal" tabindex="-1" aria-labelledby="Label" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="Label">Add a task</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body">
                <div class="input-group mb-3">
                    <span class="input-group-text">Task</span>
                    <input type="text" class="form-control" placeholder="Name of task" name="event"
													aria-label="task-name" aria-describedby="basic-addon1">
                    <span class="input-group-text">User mail</span>
                    <input type="email" class="form-control" name="mail" placeholder="User mail"
													aria-label="task-name" aria-describedby="basic-addon1">
                    <span class="input-group-text">Status</span>
                    <input type="text" class="form-control" name="status" placeholder="Status"
													aria-label="task-name" aria-describedby="basic-addon1">
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="submit" name="btn" value="add" class="btn btn-primary">Save changes</button>
            </div>
            </div>
        </div>
        </div>
        </form>
    </div>
    {% endif %}

    <div class="container table-responsive">
    <table class="table">
        <thead>
        <tr>
            <th class="task-id">Id</th>
            <th class="task">Task</th>
            <th class="username">Username</th>
            <th class="status">Status</th>
            <th class="update">Complete</th>
        </tr>
        </thead>
        {% if todos %}
        <tbody>
        {% for todo in todos %}
            <tr>
                <td>{{todo.id}}</td>
                <td>"{{todo.event}}"</td>
                <td>{{todo.username}}</td>
                <td>{{todo.status}}</td>
                {% if todo.username == name %}
                <form method="post">
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                    <td><button type="submit" name="btn" class="btn btn-outline-info btn-sm" value={{todo.id}}><i class="fa fa-pen fa-1"></i>Complete
                </button></td></form>
                {% endif %}
            </tr>
        {% endfor %}
        </tbody>
        {% endif %}
    </table>
    </div>
<div class="container"><button class="btn btn-primary" onclick="location.href={{url_for('diary.index')}}" type="button">Back To Calendar</button></div>

{% endblock %}