main_page/__init__.py
from flask import Blueprint

company_management_blueprint = Blueprint('main_page', __name__)

main_page/controllers.py
from flask import Blueprint, render_template

main_page_blueprint = Blueprint('main_page', __name__, template_folder='templates')


@main_page_blueprint.route('/', methods=('GET',))
def main_page():
    return render_template('main_page/index.html')

main_page/templates/main_page/index.html
{% extends 'base.html' %}
    {%block title%}Home - Brand{%endblock%}
    {% block head %}
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic">
    <script src="{{url_for('static', filename='js/clean-blog.js')}}"></script>
    {% endblock %}


{% block content %}
    <nav class="navbar navbar-light navbar-expand-lg fixed-top" id="mainNav">
        <div class="container"><a class="navbar-brand" href="{{ url_for('main_page.main_page') }}">Brand</a><button data-bs-toggle="collapse" data-bs-target="#navbarResponsive" class="navbar-toggler" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><i class="fa fa-bars"></i></button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item"><a class="nav-link" href="{{ url_for('main_page.main_page') }}">Home</a></li>
                    {% if not current_user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link" href="{{ url_for('accounts.login') }}">Profile</a></li>
                        <li class="nav-item"><a class="nav-link" href="{{ url_for('accounts.login') }}">Diary</a></li>
                        <li class="nav-item"><a class="nav-link" href="{{ url_for('accounts.login') }}">login</a></li>
                    {% else %}
                        <li class="nav-item"><a class="nav-link" href="{{ url_for('accounts.user_info') }}">Profile</a></li>
                        <li class="nav-item"><a class="nav-link" href="{{ url_for('diary.index') }}">Diary</a></li>
                        <li class="nav-item"><a class="nav-link" href="{{ url_for('accounts.logout') }}">logout</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    <header class="masthead" style="background-image:url('{{url_for('static', filename='img/home-bg.jpg')}}')">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-10 col-lg-8 mx-auto position-relative">
                    <div class="site-heading">
                        <h1>Your Diary</h1>
                    </div>
                </div>
            </div>
        </div>
        {%if not current_user.is_authenticated %}
            </header><button onclick="location.href='/accounts/login'" class="btn btn-primary custom-btn" type="button">Log In</button>
        {% else %}
           </header><button onclick="location.href='/diary/'" class="btn btn-primary custom-btn" type="button">Create Now</button>
        {% endif %}<h1></h1>
{% endblock %}
    {% block footer %}
        <div class="container">
            <div class="row">
                <div class="col-md-10 col-lg-8 mx-auto">
                    <ul class="list-inline text-center">
                        <li class="list-inline-item"><span class="fa-stack fa-lg"><i class="fa fa-circle fa-stack-2x"></i><i class="fa fa-twitter fa-stack-1x fa-inverse"></i></span></li>
                        <li class="list-inline-item"><span class="fa-stack fa-lg"><i class="fa fa-circle fa-stack-2x"></i><i class="fa fa-facebook fa-stack-1x fa-inverse"></i></span></li>
                        <li class="list-inline-item"><span class="fa-stack fa-lg"><i class="fa fa-circle fa-stack-2x"></i><i class="fa fa-github fa-stack-1x fa-inverse"></i></span></li>
                    </ul>
                    <p class="text-muted copyright">Copyright&nbsp;©&nbsp;Brand 2021</p>
                </div>
            </div>
        </div>
 {% endblock %}